import { writeFileSync, existsSync, readFileSync, copyFileSync } from 'fs';
import { join } from 'path';
import { WizardConfig } from '../wizard.types';

/**
 * Sanitize a value for .env file: strip control characters that could
 * inject additional environment variables.
 */
function sanitizeEnvValue(value: string): string {
  return value.replace(/[\r\n\0]/g, '');
}

/**
 * Generate .env file content from wizard config.
 */
export function generateEnvContent(config: WizardConfig): string {
  const lines: string[] = [
    '# ============================================================',
    '# Slack-Claude Code multi-session integration system config',
    '# ============================================================',
    '# Generated by Setup Wizard',
    '# ============================================================',
    '',
    '# -----------------------------------------------------------',
    '# [Required] Slack connection',
    '# -----------------------------------------------------------',
    `SLACK_BOT_TOKEN=${sanitizeEnvValue(config.slackBotToken)}`,
    `SLACK_APP_TOKEN=${sanitizeEnvValue(config.slackAppToken)}`,
    `SLACK_SIGNING_SECRET=${sanitizeEnvValue(config.slackSigningSecret)}`,
    `SLACK_CHANNEL_ID=${sanitizeEnvValue(config.slackChannelId)}`,
    '',
    '# -----------------------------------------------------------',
    '# [Required] Security',
    '# -----------------------------------------------------------',
    `ALLOWED_USER_IDS=${config.allowedUserIds.map(sanitizeEnvValue).join(',')}`,
    `ALLOWED_CHANNEL_IDS=${config.allowedChannelIds.map(sanitizeEnvValue).join(',')}`,
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Working directory',
    '# -----------------------------------------------------------',
  ];

  if (config.claudeWorkingDir) {
    lines.push(
      `CLAUDE_WORKING_DIR=${sanitizeEnvValue(config.claudeWorkingDir)}`,
    );
  } else {
    lines.push('# CLAUDE_WORKING_DIR=/path/to/your/project');
  }
  lines.push(`STATE_DIR=${sanitizeEnvValue(config.stateDir)}`);

  lines.push(
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Security filters',
    '# -----------------------------------------------------------',
    `BLOCKED_COMMANDS=${config.blockedCommands.map(sanitizeEnvValue).join(',')}`,
    `CONFIRM_COMMANDS=${config.confirmCommands.map(sanitizeEnvValue).join(',')}`,
    `MAX_PROMPT_LENGTH=${config.maxPromptLength}`,
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Session management',
    '# -----------------------------------------------------------',
    `MAX_ACTIVE_SESSIONS=${config.maxActiveSessions}`,
    `SESSION_TIMEOUT_MS=${config.sessionTimeoutMs}`,
    `HEARTBEAT_INTERVAL_MS=${config.heartbeatIntervalMs}`,
    `STALE_SESSION_MS=${config.staleSessionMs}`,
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Notification delay',
    '# -----------------------------------------------------------',
    `NOTIFICATION_DELAY_SECONDS=${config.notificationDelaySeconds}`,
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Polling',
    '# -----------------------------------------------------------',
    `POLL_INTERVAL_MS=${config.pollIntervalMs}`,
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Execution queue',
    '# -----------------------------------------------------------',
    `MAX_CONCURRENT_EXECUTIONS=${config.maxConcurrentExecutions}`,
    `MAX_QUEUE_SIZE=${config.maxQueueSize}`,
    `EXECUTION_TIMEOUT_MS=${config.executionTimeoutMs}`,
    '',
    '# -----------------------------------------------------------',
    '# [Optional] Logging',
    '# -----------------------------------------------------------',
    `LOG_LEVEL=${config.logLevel}`,
    '',
  );

  return lines.join('\n');
}

/**
 * Write .env file with backup if existing.
 */
export function writeEnvFile(config: WizardConfig, projectRoot: string): void {
  const envPath = join(projectRoot, '.env');

  // Backup existing .env
  if (existsSync(envPath)) {
    const timestamp = Date.now();
    const backupPath = join(projectRoot, `.env.backup.${timestamp}`);
    copyFileSync(envPath, backupPath);
  }

  const content = generateEnvContent(config);
  writeFileSync(envPath, content, 'utf8');
}

/**
 * Parse an existing .env file into a key-value map.
 */
export function parseEnvFile(projectRoot: string): Record<string, string> {
  const envPath = join(projectRoot, '.env');
  if (!existsSync(envPath)) return {};

  const content = readFileSync(envPath, 'utf8');
  const result: Record<string, string> = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    result[key] = value;
  }

  return result;
}
